/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#ede1cf",
        "on-primary": "#ffffff",
        "surface-bright": "#fff8f2",
        "primary-fixed-dim": "#a1d494",
        "surface-container-low": "#fef2e0",
        "secondary": "#2a657e",
        "primary-fixed": "#bcf0ae",
        "on-surface": "#201b10",
        "surface-dim": "#e4d9c7",
        "on-primary-container": "#9dd090",
        "outline": "#72796e",
        "on-primary-fixed": "#002201",
        "on-background": "#201b10",
        "primary-container": "#2d5a27",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#fbefdd",
        "background": "#fff8f2",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#96ceeb",
        "secondary-fixed": "#bfe8ff",
        "primary": "#154212",
        "on-secondary-fixed-variant": "#044d65",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-container": "#ffb177",
        "tertiary": "#5c2c00",
        "inverse-primary": "#a1d494",
        "surface": "#fff8f2",
        "tertiary-container": "#7e3f00",
        "on-surface-variant": "#42493e",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#301400",
        "surface-container-highest": "#ede1cf",
        "error-container": "#ffdad6",
        "surface-container-high": "#f2e7d5",
        "surface-container": "#f8ecda",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb782",
        "on-tertiary-fixed-variant": "#703800",
        "on-primary-fixed-variant": "#23501e",
        "outline-variant": "#c2c9bb",
        "on-secondary-fixed": "#001f2b",
        "surface-tint": "#3b6934",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#2b657e",
        "inverse-surface": "#363024",
        "secondary-container": "#aae2ff"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
